<docs>
<JavaScriptReferenceStatementsThrow>
<summary>
The <strong><c>throw</c></strong> statement throws a user-defined exception. Execution of the current function will stop (the statements after <c>throw</c> won&amp;apos;t be executed), and control will be passed to the first <see href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch"><c>catch</c></see> block in the call stack. If no <c>catch</c> block exists among caller functions, the program will terminate.
</summary>
<remarks>
<para>EmbedInteractiveExample("pages/js/statement-throw.html")</para>
<para>-<see cref="Statements/tryCatch"/><br/>-<see cref="Error"/><br/></para>
<para><seealso href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/throw"> <em>See also on MDN</em> </seealso></para>
</remarks>
</JavaScriptReferenceStatementsThrow>
</docs>